name = "ironclad-online"
main = "worker.js"
compatibility_date = "2026-07-01"
account_id = "e3507901699c196c82b78ea540a58612"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ironclad-online-db"
database_id = "f0912421-e088-49dc-a912-18555e29bc75"
